-- DROP
DROP TABLE EMP_TABLE;
DROP TABLE REPLY_TABLE;
DROP TABLE FILE_LIST;
DROP TABLE RECIPE_TABLE;
DROP TABLE ORDER_TABLE;
DROP TABLE CART_TABLE;
DROP TABLE ITEM_TABLE;
DROP TABLE CATEGORY_TABLE;
DROP TABLE USER_TABLE;

DROP SEQUENCE USER_NUM_SEQ;
DROP SEQUENCE ORDER_NUM_SEQ;
DROP SEQUENCE ITEM_NUM_SEQ;
DROP SEQUENCE CART_NUM_SEQ;
DROP SEQUENCE RECIPE_NUM_SEQ;
DROP SEQUENCE EMP_NUM_SEQ;
DROP SEQUENCE FILE_NUM_SEQ;
DROP SEQUENCE CATEGORY_NUM_SEQ;

-- 회원 테이블
CREATE TABLE USER_TABLE(
    USER_NUM     NUMBER          PRIMARY KEY,
    USER_NAME    VARCHAR2(10)    NOT NULL,
    USER_MAIL    VARCHAR2(50)    UNIQUE NOT NULL,
    USER_PW      VARCHAR2(300)    NOT NULL,
    USER_CALL    VARCHAR2(13)    UNIQUE NOT NULL,
    USER_ADDRESS VARCHAR2(100)
);

-- 카테고리 테이블
CREATE TABLE CATEGORY_TABLE(
    CATEGORY_NUM    NUMBER         PRIMARY KEY,
    CATEGORY_NAME   VARCHAR2(20)   NOT NULL
);

-- 상품 테이블
CREATE TABLE ITEM_TABLE(
    ITEM_NUM        NUMBER          PRIMARY KEY,
    CATEGORY_NUM    NUMBER          REFERENCES CATEGORY_TABLE(CATEGORY_NUM) ON DELETE SET NULL,
    ITEM_NAME       VARCHAR2(1000)  NOT NULL,
    PRICE           NUMBER(6)       NOT NULL,
    ITEM_AMOUNT     NUMBER(3)       DEFAULT 1 -- 상품 1개 이상 등록하게 설정
);

-- 장바구니 테이블
CREATE TABLE CART_TABLE(
    CART_NUM    NUMBER    PRIMARY KEY,
    ITEM_NUM    NUMBER    REFERENCES ITEM_TABLE(ITEM_NUM) ON DELETE CASCADE,
    CART_AMOUNT NUMBER(2) DEFAULT 1
);

-- 주문 테이블
CREATE TABLE ORDER_TABLE(
    ORDER_NUM     NUMBER        PRIMARY KEY,
    CART_NUM      NUMBER        REFERENCES CART_TABLE(CART_NUM) ON DELETE CASCADE,
    USER_NUM      NUMBER        REFERENCES USER_TABLE(USER_NUM) ON DELETE CASCADE,
    ITEM_NUM      NUMBER        REFERENCES ITEM_TABLE(ITEM_NUM) ON DELETE CASCADE,
    ORDER_ADDRESS VARCHAR2(100) NOT NULL,
    ORDER_MAIL    VARCHAR2(50)  NOT NULL,
    ORDER_CALL    VARCHAR2(13)  NOT NULL,
    AMOUNT        NUMBER(2)     DEFAULT 1, -- 1개 이상 주문
    INDATE        DATE          DEFAULT SYSDATE
);

-- 레시피 게시판 테이블
CREATE TABLE RECIPE_TABLE(
    RECIPE_NUM        NUMBER         PRIMARY KEY,
    USER_NUM          NUMBER         REFERENCES USER_TABLE(USER_NUM) ON DELETE SET NULL,
    TITLE             VARCHAR2(60)   NOT NULL,
    CONTENT           VARCHAR2(2000) NOT NULL,
    READ_COUNT        NUMBER         DEFAULT 0,
    SCORE             NUMBER(1)      DEFAULT 5,
    INDATE            DATE           DEFAULT SYSDATE
);

-- 파일 리스트 테이블
CREATE TABLE FILE_LIST (
    FILE_NUM          NUMBER         PRIMARY KEY,
    RECIPE_NUM        NUMBER         REFERENCES RECIPE_TABLE(RECIPE_NUM) ON DELETE CASCADE,
    ITEM_NUM          NUMBER         REFERENCES ITEM_TABLE(ITEM_NUM) ON DELETE CASCADE,
    ORIGINAL_FILENAME VARCHAR2(1000),
    SAVED_FILENAME    VARCHAR2(1000)
);

-- 게시판 댓글 테이블
CREATE TABLE REPLY_TABLE(
    REPLY_NUM     NUMBER         PRIMARY KEY,
    RECIPE_NUM    NUMBER         REFERENCES RECIPE_TABLE(RECIPE_NUM) ON DELETE CASCADE,
    USER_NUM      NUMBER         REFERENCES USER_TABLE(USER_NUM) ON DELETE SET NULL,
    REPLY_CONTENT VARCHAR2(2000) NOT NULL,
    REPLY_DATE    DATE           DEFAULT SYSDATE
);

-- 직원(관리자) 테이블
CREATE TABLE EMP_TABLE(
    EMP_NUM  NUMBER       PRIMARY KEY,
    EMP_PW   VARCHAR2(20) NOT NULL,
    EMP_NAME VARCHAR2(10) NOT NULL,
    EMP_CALL VARCHAR2(13) UNIQUE NOT NULL,
    POSITION VARCHAR2(6)  NOT NULL
);

-- 각종 시퀀스 (일련 번호)
CREATE SEQUENCE USER_NUM_SEQ;
CREATE SEQUENCE ORDER_NUM_SEQ;
CREATE SEQUENCE ITEM_NUM_SEQ;
CREATE SEQUENCE CART_NUM_SEQ;
CREATE SEQUENCE RECIPE_NUM_SEQ;
CREATE SEQUENCE FILE_NUM_SEQ;
CREATE SEQUENCE EMP_NUM_SEQ
   START WITH 1111;
CREATE SEQUENCE CATEGORY_NUM_SEQ
    INCREMENT BY 10
    START WITH 10;

-- 테스트용 데이터
SELECT * FROM EMP_TABLE;

-- EMP_TABLE(직원 정보)
INSERT INTO EMP_TABLE (EMP_NUM, EMP_PW, EMP_NAME, EMP_CALL, POSITION)
VALUES
(
   EMP_NUM_SEQ.NEXTVAL,
   '1234',
   '박나래',
   '01011112222',
   '사장'
);
INSERT INTO EMP_TABLE (EMP_NUM, EMP_PW, EMP_NAME, EMP_CALL, POSITION)
VALUES
(
   EMP_NUM_SEQ.NEXTVAL,
   '1234',
   '노채린',
   '01033334444',
   '직원'
);
INSERT INTO EMP_TABLE (EMP_NUM, EMP_PW, EMP_NAME, EMP_CALL, POSITION)
VALUES
(
   EMP_NUM_SEQ.NEXTVAL,
   '1234',
   '안찬호',
   '01055556666',
   '직원'
);
INSERT INTO EMP_TABLE (EMP_NUM, EMP_PW, EMP_NAME, EMP_CALL, POSITION)
VALUES
(
   EMP_NUM_SEQ.NEXTVAL,
   '1234',
   '이상우',
   '01077778888',
   '대리'
);

-- USER_TABLE(회원 정보)
INSERT INTO USER_TABLE(
    USER_NUM,
    USER_NAME,
    USER_MAIL,
    USER_PW,
    USER_CALL,
    USER_ADDRESS
) VALUES (
    USER_NUM_SEQ.NEXTVAL,
    '김필립',
    'abc@gmail.com',
    '1234',
    '01012345678',
    '서울특별시 종로구 사직로 161'
);

INSERT INTO USER_TABLE(
    USER_NUM,
    USER_NAME,
    USER_MAIL,
    USER_PW,
    USER_CALL,
    USER_ADDRESS
) VALUES (
    USER_NUM_SEQ.NEXTVAL,
    '강웅일',
    'cdb@gmail.com',
    '45675',
    '01053459542',
    '서울특별시 서초구 남부순환로 2248(방배3동 630)'
);

INSERT INTO USER_TABLE(
    USER_NUM,
    USER_NAME,
    USER_MAIL,
    USER_PW,
    USER_CALL,
    USER_ADDRESS
) VALUES (
    USER_NUM_SEQ.NEXTVAL,
    '김민수',
    'dskjdjklsd1@gmail.com',
    '6678  ',
    '01045465213',
    '서울특별시 서초구 남부순환로 2248(방배3동 630)'
);

INSERT INTO USER_TABLE(
    USER_NUM,
    USER_NAME,
    USER_MAIL,
    USER_PW,
    USER_CALL,
    USER_ADDRESS
) VALUES (
    USER_NUM_SEQ.NEXTVAL,
    '노채린',
    'kdsd@gmail.com',
    '45675',
    '01031212395',
    '광주광역시 광산구 우산동 1589-1'
);

-- CATEGORY_TABLE (카테고리 정보)
INSERT INTO CATEGORY_TABLE(CATEGORY_NUM,CATEGORY_NAME) VALUES (CATEGORY_NUM_SEQ.NEXTVAL, '육류');

INSERT INTO CATEGORY_TABLE(CATEGORY_NUM, CATEGORY_NAME) VALUES (CATEGORY_NUM_SEQ.NEXTVAL, '어패류');

INSERT INTO CATEGORY_TABLE(CATEGORY_NUM, CATEGORY_NAME) VALUES (CATEGORY_NUM_SEQ.NEXTVAL, '과일');

INSERT INTO CATEGORY_TABLE(CATEGORY_NUM, CATEGORY_NAME) VALUES (CATEGORY_NUM_SEQ.NEXTVAL, '채소');

INSERT INTO CATEGORY_TABLE(CATEGORY_NUM, CATEGORY_NAME) VALUES (CATEGORY_NUM_SEQ.NEXTVAL, '조미료');

INSERT INTO CATEGORY_TABLE(CATEGORY_NUM, CATEGORY_NAME) VALUES (CATEGORY_NUM_SEQ.NEXTVAL, '음료');

INSERT INTO CATEGORY_TABLE(CATEGORY_NUM, CATEGORY_NAME) VALUES (CATEGORY_NUM_SEQ.NEXTVAL, '그 외');

-- ITEM_TABLE (상품 정보)
INSERT INTO ITEM_TABLE(
	ITEM_NUM,
    CATEGORY_NUM,
	ITEM_NAME,
	PRICE,
	ITEM_AMOUNT
) VALUES (
	ITEM_NUM_SEQ.NEXTVAL,
	10,
	'소고기 500G',
	10000,
	100
);

INSERT INTO ITEM_TABLE(
	ITEM_NUM,
	CATEGORY_NUM,
	ITEM_NAME,
	PRICE,
	ITEM_AMOUNT
) VALUES (
	ITEM_NUM_SEQ.NEXTVAL,
	20,
	'고등어 110G 10팩',
	11000,
	50
);

INSERT INTO ITEM_TABLE(
	ITEM_NUM,
	CATEGORY_NUM,
	ITEM_NAME,
	PRICE,
	ITEM_AMOUNT
) VALUES (
	ITEM_NUM_SEQ.NEXTVAL,
	30,
	'사과 1봉지(1.5KG)',
	7000,
	100
);

INSERT INTO ITEM_TABLE(
	ITEM_NUM,
	CATEGORY_NUM,
	ITEM_NAME,
	PRICE,
	ITEM_AMOUNT
) VALUES (
	ITEM_NUM_SEQ.NEXTVAL,
	40,
	'양배추 1통',
	3000,
	100
);

INSERT INTO ITEM_TABLE(
	ITEM_NUM,
	CATEGORY_NUM,
	ITEM_NAME,
	PRICE,
	ITEM_AMOUNT
) VALUES (
	ITEM_NUM_SEQ.NEXTVAL,
	50,
	'후추 100G',
	5400,
	100
);

INSERT INTO ITEM_TABLE(
	ITEM_NUM,
	CATEGORY_NUM,
	ITEM_NAME,
	PRICE,
	ITEM_AMOUNT
) VALUES (
	ITEM_NUM_SEQ.NEXTVAL,
	50,
	'소금 50G',
	5250,
	100
);

INSERT INTO ITEM_TABLE(
	ITEM_NUM,
	CATEGORY_NUM,
	ITEM_NAME,
	PRICE,
	ITEM_AMOUNT
) VALUES (
	ITEM_NUM_SEQ.NEXTVAL,
	60,
	'쌀 20KG',
	47800,
	30
);